### ISSUE TITLE
9.23 patch BugSplat error message

### ISSUE THREAD

**Issue by ghost** [mmtrt/leagueoflegends#96] opened 2019-11-20 01:02 UTC
[League of Legends screen record with error;](https://download.www21.filehosting.org/8b3f6b384ab431089a0702857af0114f/video.mp4)
[...and one more link if the first will not work.](https://www81.zippyshare.com/v/WHxbvOFl/file.html)
In this video file all about the problem, as much as I may show.
[Error log after run league of legends from xterm.
](https://pastebin.com/9nwDdsuW)Lubuntu 18.10 cosmic x86_64 with Linux kernel 4.18.0-25-generic
Anything additional information is needed?
```
$ snap list
Name                     Version          Rev   Tracking   Publisher     Notes
core                     16-2.42.1        8039  stable     canonical✓    core
core18                   20191030         1265  stable     canonical✓    base
gtk-common-themes        0.1-25-gcc83164  1353  stable     canonical✓    -
leagueoflegends          1.0              55    edge       mmtrt         devmode
wine-platform-4-staging  4.16             24    candidate  mmtrt         -
wine-platform-runtime    v1.0             56    beta       mmtrt         -
```

**Comment by mmtrt** [comment] 2019-11-20 05:19
can you post info about your system?

I've just updated & tested game working fine here no such issues. Maybe try creating fresh wineprefix see #7 for HowTo.

**Comment by Getta91** [comment] 2019-11-20 07:25
Hi I had the same error with the same snaps as you. All i did was using a fresh wineprefix but with the candidate version of wine-platform-runtime. Try this one! 👍

**Comment by ondrakubicek** [comment] 2019-11-20 09:36
Hi, same here...
snap list
Name                     Version          Rev   Tracking   Publisher   Notes
core                     16-2.42.1        8039  stable     canonical✓  core
core18                   20191030         1265  stable     canonical✓  base
gtk-common-themes        0.1-25-gcc83164  1353  stable     canonical✓  -
hello-world              6.4              29    stable     canonical✓  -
leagueoflegends          1.0              55    edge       mmtrt       devmode
snapd                    2.42.1           5306  stable     canonical✓  snapd
wine-platform-4-staging  4.16             24    candidate  mmtrt       -
wine-platform-runtime    v1.0             58    candidate  mmtrt       -

wine-platform-runtime witth candidate version..

**Comment by Bloodiko** [comment] 2019-11-20 10:07
so your game is actually running beyond the champ select on version 9.23 ? thats cool - many people on the league of linux reddit complain too, that their games not working, some with bugsplats , some without

**Comment by ondrakubicek** [comment] 2019-11-20 10:17
nope, bunch of bugsplat popups, when i start the game so i have to kill the process..

**Comment by mmtrt** [comment] 2019-11-20 10:26
so rito broke game again with preseason update and this needs new wine patch fixes.

**Comment by ondrakubicek** [comment] 2019-11-20 12:34
https://bugs.winehq.org/attachment.cgi?id=65743&action=diff#a/dlls/ntdll/thread.c_sec1 by 
https://www.reddit.com/r/leagueoflinux/comments/dyvdse/did_the_new_preseason_patch_break_league/

**Comment by astamavelakakasana** [comment] 2019-11-20 13:44
> can you post info about your system?
> 
> I've just updated & tested game working fine here no such issues. Maybe try creating fresh wineprefix see #7 for HowTo.
[CPU](https://pastebin.com/aFNE7rys), [mem](https://pastebin.com/DGLWX98E), [pci](https://pastebin.com/TbXMCNPq)

**Comment by Bloodiko** [comment] 2019-11-20 15:30
> > can you post info about your system?
> > I've just updated & tested game working fine here no such issues. Maybe try creating fresh wineprefix see #7 for HowTo.
> > [CPU](https://pastebin.com/aFNE7rys), [mem](https://pastebin.com/DGLWX98E), [pci](https://pastebin.com/TbXMCNPq)

your ptoblem may be that your wine is still set to windows XP - it should be windows 7 by now, as riot stoppped ysupporting windows xp, so try to set it to windows 7 manually (`leagueoflegends.winecfg`) and see if you are able to log in

Due to preseason patch the game is broken atm though - you wont be able to play, nor spectate - but you should at least be able to login into the client - then we wait for mmtrt to provide a patch for wine now

**Comment by astamavelakakasana** [comment] 2019-11-20 16:37
> > > can you post info about your system?
> > > I've just updated & tested game working fine here no such issues. Maybe try creating fresh wineprefix see #7 for HowTo.
> > > [CPU](https://pastebin.com/aFNE7rys), [mem](https://pastebin.com/DGLWX98E), [pci](https://pastebin.com/TbXMCNPq)
> 
> your ptoblem may be that your wine is still set to windows XP - it should be windows 7 by now, as riot stoppped ysupporting windows xp, so try to set it to windows 7 manually (`leagueoflegends.winecfg`) and see if you are able to log in
> 
> Due to preseason patch the game is broken atm though - you wont be able to play, nor spectate - but you should at least be able to login into the client - then we wait for mmtrt to provide a patch for wine now

The error has already appeared with prefix "win7", and after it I changed prefix to "winxp", and then this error has came again. :)

**Comment by stuartfoxcroft** [comment] 2019-11-20 19:13
The reason for having the prefix version as winxp was to resolve initial bugsplat issues as an earlier patch for issues required winxp, additionally winxp support was dropped months ago but the game would still run fine, plus the reason for dropping winxp support was to allow updates to the CEF framework behind the client which launches the game, not the game window itself.

The same issue was also happening last PBE cycle (maybe could be an idea to preemptively test PBE versions in the future for less live downtime on such issues, idk?).
Seems for now it's just a case of waiting for wine patches to be created and distributed to solve the issues :(

**Comment by mmtrt** [comment] 2019-11-20 19:45
**UPDATE**

I've compiled `wine` with fixes and good news is that seems to work fine for now in AppImg and bad news in Snap game is still crashing after champion select.
I'll push snap wine update to beta branch so further you guys could test it and again I also update league snap as well as I found weird winetricks bug with args which I reverted change that fixes install `directx` issue on preinstalled game.

More testing in the morning or later today as im tired and sleepy.

**Comment by Getta91** [comment] 2019-11-20 19:57
I will give it a try. Thanks

**Comment by Ra-Ni** [comment] 2019-11-20 20:07
Same issue. I saw the following message though
```
LeagueClient.exe(00000034):   WARN|           rcp-be-lol-patch| Patcher: Error verifying game install: Error opening patch database: The database wasn't closed cleanly
LeagueClient.exe(000000AE):   WARN|           <unknown-plugin>| Patcher: Error opening existing database C:/Riot Games/League of Legends/Game.db: The database wasn't closed cleanly
LeagueClient.exe(000000AE):   WARN|           <unknown-plugin>| Patcher: Repair: Error rechunking file DATA/FINAL/Champions/Annie.wad.client: Invalid Wad file identifier

```

**Comment by stuartfoxcroft** [comment] 2019-11-20 20:22
The bugsplat also occurs when entering the Champions tab of the Collection tab of the client. This suggests potentially an issue with incorrectly handling the database containing champion info, and possibly overflows or corruption of the database. Has anyone tried completely reinstalling LoL with the beta wine-platform-runtime?

**Comment by Ra-Ni** [comment] 2019-11-20 20:25
> The bugsplat also occurs when entering the Champions tab of the Collection tab of the client. This suggests potentially an issue with incorrectly handling the database containing champion info, and possibly overflows or corruption of the database. Has anyone tried completely reinstalling LoL with the beta wine-platform-runtime?

Yes I did and same issue as my previous comment

**Comment by stuartfoxcroft** [comment] 2019-11-20 20:27
So, based on the very limited testing I've been able to do so far, the issue seems to arise wherever the database storing champions (and possibly also for skins) is being handled (i.e. champ select, collection tab, store) so that may be linked to the issue? I'll have a look through my bugsplat logs to see if anything else sticks out.

**Comment by Getta91** [comment] 2019-11-20 20:32
> So, based on the very limited testing I've been able to do so far, the issue seems to arise wherever the database storing champions (and possibly also for skins) is being handled (i.e. champ select, collection tab, store) so that may be linked to the issue? I'll have a look through my bugsplat logs to see if anything else sticks out.

I can't even launch the client (getting a bugsplat) with the beta version of the wine snap. I used a fresh wineprefix  and both windows XP and 7 versions. This issue is kind of weird. By the way the appimage works for the client but i am getting a bugsplat ater champ select.

**Comment by stuartfoxcroft** [comment] 2019-11-20 20:39
I get the fonts issue as well but am able to launch the client via the snap. Looking at the logs, something  is triggering segmentation faults causing the client to enter a crash loop until the process is killed, but I can't quite tell what as of yet. Will keep looking.

**Comment by mmtrt** [comment] 2019-11-20 20:39
@getta91 you need to install `directx9` in `appimg` wineprefix.


Build server seems to be not uploading snap built so here is link for snap pkg

``` https://launchpad.net/~mmtrt/+snap/wine-platform-4-staging/+build/740402/+files/wine-platform-4-staging_4.16_amd64.snap
```

Download it then install with this command where that snap pkg is located.

`sudo snap install wine-platform-4-staging_4.16_amd64.snap --dangerous`

**Comment by Getta91** [comment] 2019-11-20 20:45
@mmtrt ty I am testing . Do you guys need a log file?

**Comment by stuartfoxcroft** [comment] 2019-11-20 20:48
Having done some more testing of the client, I believe the issue to be regarding the database containing which champions are owned by the player. I believe this due to the nature of the bugsplats occurring during champion select, when viewing the player's collection of champions, and when selecting "show owned" in the champions tab of the store. As of yet I am unsure as to why this is causing bugsplats, but the bugsplats are repeatable. One upon first launching the client, and then a second that causes a crash loop upon any one of the 3 activities I outlined above.

**Comment by stuartfoxcroft** [comment] 2019-11-20 20:51
Open question, is it possible that the champion database is too large to be opened under a winxp environment? I believe a while back there was a patch that adjusted how much memory could be used, and it might have something to do with the fact that the UXRenderer crashes due to segmentation faults...

**Comment by gus-araujo** [comment] 2019-11-20 20:52
Tested the training mode and i works, so I think the problem isn't champions database. But when I try to change runes it crashes and reopen client in training lobby

**Comment by Getta91** [comment] 2019-11-20 20:53
@mmtrt file:///snap/bin/leagueoflegends
file:///snap/bin/leagueoflegends.wineboot
file:///snap/bin/leagueoflegends.winecfg
file:///snap/bin/leagueoflegends.wineserver
file:///snap/bin/leagueoflegends.winetricks
file:///snap/bin/spotify
those are the only files in /snap/bin

**Comment by mmtrt** [comment] 2019-11-20 20:58
@getta91 that's just warning try to game.

**Comment by Getta91** [comment] 2019-11-20 20:58
Fixed I did this:

snap connect leagueoflegends:wine-4-staging wine-platform-4-staging

**Comment by stuartfoxcroft** [comment] 2019-11-20 21:10
The reconnect loop is down to HTTP 503 errors (Service Unavailable) trying to connect to the Parties service (know it's not much info but it might end up being useful at some point).

**Comment by Getta91** [comment] 2019-11-20 21:13
well guys. I can't make this work again. So I will just completely reinstall tomorrow my league. Keep me in touch ^^. See you

**Comment by Ra-Ni** [comment] 2019-11-20 21:43
welp. It's been fixed in winehq. just download/install it, and grab an offish version of league. that's it.

**Comment by astamavelakakasana** [comment] 2019-11-21 00:57
> Fixed I did this:
> 
> snap connect leagueoflegends:wine-4-staging wine-platform-4-staging
> 
> Edit: Still getting the bugsplat
> 
> 0051:err:winediag:wined3d_dll_init Setting multithreaded command stream to 0.
> LeagueClient.exe(00000009): ALWAYS| Application Version:9.23.298.3143 - CL:2983143 - Build Date:Nov 18 2019 - Build Time:16:50:09
> LeagueClient.exe(00000009): ALWAYS| Generating new machine id
> ... oh my gosh ...
> exit_code: -3
> termination_type: segmentation fault
> LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.

Here, partner... Take it! _takes out a revolver and throws Getta91. The inscription flaunts on the handle of the revolver: "pastebin"_ ;>

> **UPDATE**
> 
> I've compiled `wine` with fixes and good news is that seems to work fine for now in AppImg and bad news in Snap game is still crashing after champion select.
> I'll push snap wine update to beta branch so further you guys could test it and again I also update league snap as well as I found weird winetricks bug with args which I reverted change that fixes install `directx` issue on preinstalled game.
> 
> More testing in the morning or later today as im tired and sleepy.
I've install an update for snap package, then I've turn on full update for league of legends and after that a little dirty bomber-yordle has appear again.

**Comment by DirkyJerky** [comment] 2019-11-21 04:03
The latest `wine-platform-4-staging` build appears to have fixed the problem.  

Commands I did are as follows, as @mmtrt suggested:

```
curl -OL 'https://launchpad.net/~mmtrt/+snap/wine-platform-4-staging/+build/740402/+files/wine-platform-4-staging_4.16_amd64.snap'
sudo snap install wine-platform-4-staging_4.16_amd64.snap --dangerous
sudo snap connect leagueoflegends:wine-4-staging wine-platform-4-staging
```

Don't know if that third command is necessary, I'm not super familiar with the snap ecosystem to determine that.

I am in-game right now, everything seems to be working as well as it did yesterday.

**Comment by DirkyJerky** [comment] 2019-11-21 04:04
Thank you for your work as always mmtrt

**Comment by Getta91** [comment] 2019-11-21 06:53
@DirkyJerky do you still have the fonts issue?

**Comment by f0cus3d** [comment] 2019-11-21 13:31
Still getting bug splat for me even with the above.

**Comment by astamavelakakasana** [comment] 2019-11-21 13:52
> The latest `wine-platform-4-staging` build appears to have fixed the problem.
> 
> Commands I did are as follows, as @mmtrt suggested:
> 
> ```
> curl -OL 'https://launchpad.net/~mmtrt/+snap/wine-platform-4-staging/+build/740402/+files/wine-platform-4-staging_4.16_amd64.snap'
> sudo snap install wine-platform-4-staging_4.16_amd64.snap --dangerous
> sudo snap connect leagueoflegends:wine-4-staging wine-platform-4-staging
> ```
> 
> Don't know if that third command was necessary, I'm not super familiar with the snap ecosystem to determine that.
> 
> I am in-game right now, everything seems to be working as well as it did yesterday.

I've did it but still after start errors is appear. [Here](https://www39.zippyshare.com/v/5fWyqknT/file.html)

**Comment by Getta91** [comment] 2019-11-21 16:03
I think mmtrt said the servers are down for now

**Comment by Getta91** [comment] 2019-11-21 16:59
Still having a bugsplat

**Comment by astamavelakakasana** [comment] 2019-11-22 02:16
> Still having a bugsplat with a fresh install, which wine platform runtime version are u using? I am running the
> candidate one
**> candidate one**
I'm too.

**Comment by f0cus3d** [comment] 2019-11-22 05:39
Fresh install, candidate wine, PoP OS

**Comment by mmtrt** [comment] 2019-11-22 07:37
**UPDATE**

Again compiled wine `4.20` with fixes from wine-lol repo and pushed `wine-platform-4-staging`  to `beta` & 'candidate'.

Tested this and it works fine now in snap side.

**NOTE:**
Thoses who had installed `wine-platform-4-staging` snap from link that I had posted here need to do this to get new update from snap server.

```
sudo snap revert wine-platform-4-staging
sudo snap update
```

**Comment by drupalranger** [comment] 2019-11-22 12:10
Any ideas why it looks some strange? 
Missing button texts, images and sound is not playing now:
https://imgur.com/INyCFzM
I did full reinstall today, everything was fine before 9.23 update

**Comment by Ignacy-s** [comment] 2019-11-22 13:24
> Any ideas why it looks so strange?

That's the font issue that people were talking about. It used to happen pretty often with games run with wine.

**Comment by drupalranger** [comment] 2019-11-22 16:44
for fonts, I've found kinda workaround here:
https://www.reddit.com/r/leagueoflinux/comments/dz59ym/client_fontdisplay_rendering_issues/
going to settings and changing window size works for me. 
I am able to log in to the client, and all pages are working , except collection/runes which fires bugsplat. 
For

**Comment by Ignacy-s** [comment] 2019-11-22 17:05
@drupalranger Thanks for reply! The original comment was edited with this info:
Edit2: https://github.com/cosarara/wine-lol resolves this issue.

Looks like there was another change to the wine-lol package, or if there was just one, my snap client is not pulling the newest packages. Will try again tomorrow.

**Comment by stuartfoxcroft** [comment] 2019-11-22 19:45
After updating `wine-platform-4-staging` to the latest available version, still encountering font issues, bugsplats on collection tab and patch notes section, as well as unable to join a game.

**Comment by ibrahimpmahmood** [comment] 2019-11-22 19:59
Not sure where to post this issue but I get a bugsplat when I try to edit any of my runes

**Comment by mmtrt** [comment] 2019-11-22 20:29
New wine update needs fresh `wineprefix` otherwise issues like that will happen.

<details>
  <summary>Creating WINEPREFIX guide</summary>


* `WINEPREFIX PATH` --> `$HOME/snap/leagueoflegends/common/.wine`
* Copy/Move out `Riot Games` dir from `WINEPREFIX`
* Delete `$HOME/snap/leagueoflegends` completely.
* Launch snap wait till it is setup when region install dialog shows close it.
* Copy/Move `Riot Games` folder back to `WINEPREFIX`
* Now you have fresh `WINEPREFIX`
</details>

**Comment by astamavelakakasana** [comment] 2019-11-22 20:35
> New wine update needs fresh `wineprefix` otherwise issues like that will happen.
> Creating WINEPREFIX guide

I will test it now :) with fresh install and everything else.

**Comment by Ignacy-s** [comment] 2019-11-22 21:07
@stuartfoxcroft @ibrahimpmahmood 
Some people still encounter errors (fonts not showing, game crashing). It might have something to do with differences in gpu or the way you run league (not sure, I'm not an expert)

**Comment by drupalranger** [comment] 2019-11-23 14:33
Unfortunately refreshing wineprefix or refreshing wine-platform-4-staging doesn't change anything for me, I am after full reinstallation already ( I've removed all snap packages , wine files etc. ) and I still see 3 issues: 
- Fonts issue ( I have to change window size everytime when I start the client ) 
- Can't access collections page - throwing bugsplat , then reloading client to the main page 
- Bugsplat is also throwing errors when I'm trying to choose runes after character select screen ( also reloads the client and goes back to the game after bugsplat ) 

Digging in logs shows following errors: 
```
~/snap/leagueoflegends/common/.wine/drive_c/Riot Games/League of Legends/Logs/LeagueClient Logs $ grep -R ERROR
2019-11-23T15-31-46_326_LeagueClientUx.log:000000.621|  ERROR| BrowserProcess::OnCertificateError browserId = 1, certError = ERR_CERT_AUTHORITY_INVALID, requestUri = "https://riot:_dLnXdiDiQONDepLEtL62g@127.0.0.1:39845/bootstrap.html", certStatus = 4
2019-11-23T15-31-46_326_LeagueClientUx.log:000001.102|  ERROR| BrowserProcess::OnCertificateError browserId = 1, certError = ERR_CERT_AUTHORITY_INVALID, requestUri = "wss://riot:_dLnXdiDiQONDepLEtL62g@127.0.0.1:39845/", certStatus = 4
2019-11-23T15-31-46_326_LeagueClientUx.log:000008.151|  ERROR| Cannot find the local file for "https://127.0.0.1:39845/fe/lol-career-stats/bundle.js" because it is not present in the asset server for that plugin.
2019-11-23T15-31-46_326_LeagueClientUx.log:000009.631|  ERROR| Cannot find the local file for "https://127.0.0.1:39845/fe/lol-content-targeting-settings/init.js" because it is not present in the asset server for that plugin.
2019-11-23T15-31-46_326_LeagueClientUx.log:000009.790|  ERROR| js: rcp-fe-lol-email-verification:error Error: Session was there from the beginning, user did not log in
```

**Comment by newhoa** [comment] 2019-11-23 15:41
> **UPDATE**
> 
> Again compiled wine `4.20` with fixes from wine-lol repo and pushed `wine-platform-4-staging` to `beta` & `candidate`.
> 
> Tested this and it works fine now in snap side.
> 
> **NOTE:**
> 
> Those who had installed `wine-platform-4-staging` snap from link that I had posted here need to do this to get new update from snap server.
> 
> ```
> sudo snap revert wine-platform-4-staging
> sudo snap update
> ```

This made it all work again AND the client is way more responsive and less laggy for me. Thank you!!

**Comment by P264nuuk** [comment] 2019-11-23 16:44
Hi,
I just created this account, to thank you for the work, just :
`snap update` - is invalid cmd, need to use `snap refresh` ...

but all working, thanks

**Comment by mmtrt** [comment] 2019-11-23 16:55
@drupalranger Thats really wierd I did not faced such issues in my main system `kubuntu 19.10` though I'll test game in laptop to reproduce these issues.

@newhoa Yeah `4.20` wine have improved thing but `rito` have too fixed launcher performance issues could be that.

@P264nuuk Thanks updated post.

**Comment by jpobeda** [comment] 2019-11-24 02:36
Hey, I'm having a weird issue. I was able to play a game with no issues at all but then I start the game without keyboard and after alt tab I get keyboard back but the camera get locked.

I know it might be something from Ubuntu but not sure. I normally play on my laptop with extended screens, not sure if that might be a problem now. It hasn't before.

Cheers.

**Comment by jpobeda** [comment] 2019-11-24 04:49
I had to run ```snap run leagueoflegends.winecfg``` and check "Automatically capture the mouse in full-screen windows" although I still need to alt+tab once to get the keyboard working ..

**Comment by Ignacy-s** [comment] 2019-11-24 10:54
This is interesting. I still get fonts bug and launcher crash after few seconds.
First I tried refreshing wine snaps to --beta and --candidate.
Then I tried recreating WINEPREFIX from backed up game files and completely removed and reinstalled all snaps while at it.
Tried two times, using backed up game files, and one time with a completely fresh install and running all the hacks needed for the game to run (winxp, chmod 0 of new launcher). `leagueoflegends.winecfg` shows that the wine is in version 4.20

 @jpobeda 

> I was able to play a game with no issues at all but then I start the game without keyboard and after alt tab I get keyboard back but the camera get locked.

This happens sometimes. Restarting the game should help. Happened to me like a week ago.

**Comment by Ignacy-s** [comment] 2019-11-24 20:40
I've spend a considerable amount of time on it today. I've upgraded Ubuntu 19.04 to 19.10,
then installed OBS wine repo [(howto)](https://www.linuxuprising.com/2019/09/how-to-install-wine-staging-development.html).
From the OBS repo I've installed i386 versions of winehq-staging and wine-staging using:
`sudo apt install --install-suggests winehq-staging:i386 wine-staging:i386`
Now league can be run using system wine with:
`wine $HOME/snap/leagueoflegends/....../LeagueClient.exe`
Had to block the new launcher by changing owner of the launcher files.

All this allows to install and run the launcher and go past the character select. However, the game after character select doesn't work :(

I've stumbled upon something when trying to run winetricks on snap league:
`leagueoflegends.winetricks` would say that:


> You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> 
> Using winetricks 20190912-next - sha256sum: 192dadb0ef20e6925552c6ac6e43b5ea4956ee1ff401948686ca929b54f5660e with wine-4.20 (Staging) and WINEARCH=win64


Is it possible that for some reason snap-wine is x64 instead of 32bit? Could that explain persistence of the fonts issue that doesn't happen to other people?

**Comment by Getta91** [comment] 2019-11-24 23:11
Before creating your wineprefix, you should do: export WINEARCH=win32

**Comment by mmtrt** [comment] 2019-11-25 09:03
updated League + os updated as well snaps on my laptop which were not done since months on this system and then I recreated wineprefix and booted up game all worked as expected.

OS `Manjaro Linux`

![Screenshot_20191125_135750](https://user-images.githubusercontent.com/2322598/69526475-0e6bb800-0f8c-11ea-9c93-33888e8b551b.png)

**Comment by Ignacy-s** [comment] 2019-11-25 18:24
@mmtrt @Getta91 Thanks for your support guys! You are awesome! In two weeks I'll be back home and I'll have another go. I'd rather try Manjaro or Arch than install Windows ^^

**Comment by drupalranger** [comment] 2019-11-28 19:39
So for me the game partly works, it still fails to open some screens like Hotkey list in settings, Collection page, I've tried to reinstall it again, and scanned logs again, I see strange segfaults, this is what I get when I try to open Collections page : 
```
000028.287|  ERROR| Assertion failed!
#####################
000117.931|  ERROR| BrowserProcess::OnRenderProcessTerminated browserId = 1, status = "segmentation fault"
000117.961|  ERROR| Browser Process Info:
Process Memory:
    1193M free.
    2548M reserved.
     353M commited.
    Largest free block is 1022M.

    PageFaultCount: 0
    PeakWorkingSetSize: 279M
    WorkingSetSize: 243M
    QuotaPeakPagedPoolUsage: 0M
    QuotaPagedPoolUsage: 0M
    QuotaPeakNonPagedPoolUsage: 0M
    QuotaNonPagedPoolUsage: 0M
    PagefileUsage: 186M
    PeakPagefileUsage: 186M
    PrivateUsage: 0M

Process Info:
    ThreadCount: 38
000117.961|  ERROR| Render process terminated with exit code -3

#################

LeagueClientUxRender caused ACCESS_VIOLATION in module LeagueClientUxRender

Write to location 00000000 caused an access violation.

User Information:
    User Name: drupalranger
    Computer Name: tornado

OS Info:
    Windows XP Service Pack 2 Professional, x64

System Information:
    12 processor(s), type 586.
    31% of memory in use.
    31756M total physical memory.
    21809M free physical memory.
    35664M total paging file.
    25717M free paging file.
    4095M total virtual memory.
    4095M free virtual memory.

Process Memory:
    1126M free.
    2438M reserved.
     530M commited.
    Largest free block is 129M.

    PageFaultCount: 0
    PeakWorkingSetSize: 444M
    WorkingSetSize: 435M
    QuotaPeakPagedPoolUsage: 0M
    QuotaPagedPoolUsage: 0M
    QuotaPeakNonPagedPoolUsage: 0M
    QuotaNonPagedPoolUsage: 0M
    PagefileUsage: 326M
    PeakPagefileUsage: 326M
    PrivateUsage: 0M

Process Info:
    ThreadCount: 37

```

**Comment by Ignacy-s** [comment] 2019-12-24 17:50
A little update:
Created a 32bit prefix, only have 32bit wine on system, and when trying to force snap to use 32bit architecture this happens:
`igi@dragon:~$ WINEARCH=win32 leagueoflegends`

> wine: WINEARCH set to win64 but '/home/igi/snap/leagueoflegends/common/.wine' is a 32-bit installation.

Is there another way of forcing the snap to use win32 arch?

**Comment by Ignacy-s** [comment] 2019-12-24 18:06
`$: WINEARCH=win32 leagueoflegends.winecfg `
`> wine: WINEARCH set to win64 but '/home/igi/snap/leagueoflegends/common/.wine' is a 32-bit installation.`

Wine inside the snap doesn't read the env variable. Is there a way to set a variable inside of the snap? Tried with export too, `echo $WINEARCH` returns win32, but the snap complains that the WINEARCH is set to win64.

**Comment by mmtrt** [comment] 2019-12-24 19:13
wine arch env is hardcoded thats why it wouldn't accept user define env, I'll make it user changeable in morning.

**Comment by Ignacy-s** [comment] 2019-12-24 19:43
Thanks Taki!

**Comment by Ignacy-s** [comment] 2019-12-31 00:12
@mmtrt 
Can confirm that it's a purely Ubuntu related issue. Got the game working on Manjaro without any work, just pulled the league snap, refreshed wine snaps to candidates and the game worked without fixing fonts or anything like that. Thanks again taki!

**Closed** 2024-05-14 10:57 UTC
