### ISSUE TITLE
There is a lag in the middle of a League of Legends game, so it goes off or lags for a while. How shall I do it?

### ISSUE THREAD

**Issue by johny135795** [mmtrt/leagueoflegends#212] opened 2022-08-09 09:54 UTC
There is a lag in the middle of a League of Legends game, so it goes off or lags for a while. How shall I do it?
OS:Mint 20.02
CPU:i5 - 12400F
GPU: RTX 540RX
RAM:8G

**Comment by Elektroney** [comment] 2022-10-23 13:14
same here it happens between minute 10 - 5 and its always only at exactly a minute (eg 5.00 not 5.01) only happens once per match and seems to happen on all os's

OS: Ubuntu 22.04
CPU:i7 - 6700
GPU: 2 GTX 950
RAM: 16G

**Comment by jhundley9109** [comment] 2022-11-10 05:08
I have a similar issue. Game lags for 4-6 seconds or so somewhere between 5-10 minutes into the game. Better hope you're not rushing a team fight! I have experienced this on both the open source nvidia driver and the actual nvidia driver. Seems unrelated to which graphics driver you're running.

OS: Ubuntu 22.04
CPU:i7 - 9750H
GPU: 4 GB GeForce GTX 1650M
RAM: 16G

**Comment by mmtrt** [comment] 2022-11-10 05:15
Could be the reason we are using old wine here 5.18 & since there is no compatibility of libc patches for newer wine I can't create new update for wine.

You guys can use lutris see if this issue happens there & they don't use libc patched variant.

Hope league will be completely fixed on new version wine.

**Comment by jhundley9109** [comment] 2022-11-17 13:46
> Lutris doesnt work for me :/ this is the online way of playing League for me, on linux. guess i'll have to get used to the lag...

Lutris does work, the version shipped with Ubuntu is largely broken right now though. You just need to upgrade the lutris package by manually installing the package from here: https://github.com/lutris/lutris/releases

After downloading just

sudo dpkg -i ~/Downloads/lutris_0.5.11_all.deb

**Comment by Elektroney** [comment] 2022-11-30 14:29
omg i finally got it to work 13 days later thanks for telling me about the lutris thingy. Everything about my installation was fucked and finally solved it now. One big thing that helped me was deleting ~/.wine !

**Comment by jhundley9109** [comment] 2022-11-30 15:14
I have had pretty good success with League on Linux through Lutris. However, I have another crashing problem. If you alt+tab or really initiate any on screen display/toast message while playing the game, the game crashes and restarts. This only happens while you're in a match. I use GNOME desktop and I suspect the issue is a problem with the gnome compositor and League compatibility. I've tried setting use virtual desktop in Lutris and a couple other things like disable desktop effects and none of them fix the crashing. 

After you play a few matches, I'd be interested to know if you're having this issue too. I had this issue on the snap version of League but currently League runs better through Lutris at the time of writing. Perhaps this isn't the correct place to have this conversation but it may be useful to others who stumble across this issue.

**Closed** 2024-05-14 10:57 UTC
