### ISSUE TITLE
League of legends client crashing while loading game after champion select screen [after patch 9.10 + lol edge: 1.0 2019-05-10 (35)]

### ISSUE THREAD

**Issue by astamavelakakasana** [mmtrt/leagueoflegends#40] opened 2019-05-14 10:07 UTC
After closing of game client and start loading ingame client I have this message on console and crush message would appearing:
>wine: Unhandled page fault on read access to 0xffffffff at address 0x7eb0f760 (thread 01b8), starting debugger...
https://imgur.com/a/aRal6sQ 

This is full log: https://pastebin.com/Dg5wdd4p

Before applying patch 9.10 all worked fine

ty for you working on this :)

**Comment by Yaesallucha** [comment] 2019-05-14 23:38
Were you able to fix this problem?

**Comment by mmtrt** [comment] 2019-05-15 00:05
Recent patch have broke the game completely on wine, best we can do is to wait for another game patch fix this issue or wine bug fix to happen so currently I can’t do anything from the snap side atm.

You can track posted wine issue about this
https://bugs.winehq.org/show_bug.cgi?id=47198

**Comment by arashbina** [comment] 2019-05-15 00:21
Confirming that ran into the same issue.

**Comment by Aerodin** [comment] 2019-05-17 17:54
https://www.reddit.com/r/leagueoflinux/comments/bpjxg0/a_proofofconcept_hack_makes_post910_playable_again/

Looks like it's possible to play on 9.10 with a few patches applied to wine + glibc.  A few users on Gentoo have confirmed.

**Comment by halogaza** [comment] 2019-05-18 02:23
can someone explain e how to fix it im kind of a noob on this kind of stuff

**Comment by mmtrt** [comment] 2019-05-19 16:50
Wine snap do not ship glibc and so using custom glibc will not play nice with shipping it on wine snap.

My efforts on building wine with patches unfortunately have failed and it couldn't even ran winecfg.

If anyone have working built pkgs I will be happy to try and test with snap.

**Comment by mmtrt** [comment] 2019-05-20 10:17
My built pkgs were failure because I was building them on `ubuntu 19.04` which have different glibc casued issues. So some good guy shared his built pkgs on Reddit and then I've tested these pkgs with snap now game goes in-game just fine now.

if anyone have used install `d9vk` or `dgvoodoo` in snap  now it will crash the launcher some reason I don't know the cause seems to failing with the glibc, wine patched build.

It will take some time to upload as I've slow connection.

![Screenshot from 2019-05-20 14-47-31](https://user-images.githubusercontent.com/2322598/58013774-c8332900-7b10-11e9-9a6a-da4e58c3e555.png)

**Comment by mmtrt** [comment] 2019-05-20 11:25
Uploaded to separate snap channel because of patched `glibc` , `wine`

`snap refresh --candidate wine-platform`

it should fix this issue, test and report back.

Thanks

**Comment by Aerodin** [comment] 2019-05-20 16:39
No issues so far on Ubuntu 18.04.

**Comment by davidmacar** [comment] 2019-05-20 17:28
The fix is working fine for me on "Linux Mint 19.1 Tessa"

**Comment by erwanriou** [comment] 2019-05-20 18:21
Hey, tested on ubuntu 18.04 just after 
```
snap refresh --candidate wine-platform
snap remove leagueoflegends
snap install --edge --devmode leagueoflegends
```

**Comment by marovargovcik** [comment] 2019-05-20 20:56
Working fine as well. Thank you.
Ubuntu 18.04

**Comment by nsa** [comment] 2019-05-20 20:57
Working fine on Manjaro 18.0.4. Thanks :)

**Comment by astamavelakakasana** [comment] 2019-05-21 13:02
Working perfectly on Lubuntu 18.10 x64. Thank you so much :)

**Comment by mhborazan** [comment] 2019-05-21 13:09
Lubuntu 18.10 x64, I don't see KDA and champion names even TAB menu i just see items.

**Comment by mmtrt** [comment] 2019-05-21 13:26
@mhborazan see last point of #7 to fix that issue.

**Comment by mhborazan** [comment] 2019-05-21 14:17
> @mhborazan see last point of #7 to fix that issue.

Thank you. I had reinstalled already but I closed without choose region and copied game and it wasn't work. Now fixed.

**Comment by f0cus3d** [comment] 2019-05-22 03:36
Confirmed working on Fedora 30
https://github.com/mmtrt/leagueoflegends/issues/40#issuecomment-494097470

**Comment by Getta91** [comment] 2019-05-23 16:06
Working very fine on Ubuntu 19.04 !! Ty men I can now play again! <3 <3

**Comment by bferrenq** [comment] 2019-05-24 08:54
> Working very fine on Ubuntu 19.04 !! Ty men I can now play again! <3 <3 Continue your nice work ;)
> You have all my RESPECT.
> 
> ̿̿ ̿̿ ̿̿ ̿'̿'\̵͇̿̿\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
> 
> (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ ✧ﾟ･: *ヽ(◕ヮ◕ヽ)
> 
> (ง ͠° ͟ل͜ ͡°)ง

Hello, 
I still have splash under ubuntu 19.04. I have uninstalled wine and league snaps then reinstall without success, can I kindly ask you what you have done?
B.

**Comment by Getta91** [comment] 2019-05-24 09:00
Hi,
All I Did was running this command on a terminal:
snap refresh --candidate wine-platform
Then I u do:
 sudo apt update
And finally:
snap refresh leagueoflegends --devmode

Hope this help! Have a nice day

**Comment by bferrenq** [comment] 2019-05-24 11:23
Hey,
thx, however I did it and still got an issue while launching game. 
Maybe now this is unrelated to this one ie from the logs I have at least:
"LeagueClientUxRender caused ACCESS_VIOLATION in module LeagueClientUxRender
Write to location 00000000 caused an access violation."
I will investigate deeper logs to find root cause

Thx again!

**Comment by Getta91** [comment] 2019-05-24 15:01
I am sorry, it didn't work for you... Good Luck and do your best!
By the way, you should create a new topic on the issues page. By!

**Comment by yuiiio** [comment] 2019-05-24 19:41
I am sorry for the basic question.
``sudo snap install wine-platform --candidate``
``sudo snap install --edge --devmode leagueoflegends``
Does the host system library overwrite?

**Comment by mmtrt** [comment] 2019-05-24 19:54
No, snaps are containerized images so they don't make changes to host install libraries but they ship these into the snap packages.

Hope this clears the confusion.

**Comment by yuiiio** [comment] 2019-05-24 20:06
ok
thak you a lot.

**Closed** 2019-05-29 10:47 UTC
